server:
  port: 8079

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: false
        # 指定使用ipv4，否则还会去解析ipv6地址，有些网络环境ipv6地址获取hostname会超时
        ip-type: IPv4
    gateway:
      routes:
        - id: nacos-service-route
          # 注意使用lb负载均衡语法，必须有注册中心以及负载均衡模块依赖
          uri: lb://nacos-service
          predicates:
            - Path=/nacos-service/**
          filters:
            - RewritePath=/nacos-service/?(?<segment>.*), /$\{segment}
            # 或者使用下面这个
            #- StripPrefix=1
        - id: nacos-consumer-route
          # 注意使用lb负载均衡语法，必须有注册中心以及负载均衡模块依赖
          uri: lb://nacos-consumer
          predicates:
            - Path=/nacos-consumer/**
          filters:
            - StripPrefix=1